### ISSUE TITLE
FR: Add option to hide statusbar item when there is nothing to update

### ISSUE THREAD

**Issue by chrisgrieser** [swar8080/obsidian-plugin-update-tracker#10]
I think it's sufficient to show the icon when there are updates, there is no need to show it nothing needs to be done

**Comment by swar8080** [comment]
added this as a setting in the latest version

**Comment by juanbretti** [comment]
Hello, where is this new option?

**Comment by swar8080** [comment]
Hi @juanbretti, this option was replaced with the below option. Setting the value to 1 has the same effect

<img width="448" alt="image" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/17691679/9a276544-7ca3-4524-82e6-2a377bb0bf6e">
