### ISSUE TITLE
Issue with changing plugin icon position

### ISSUE THREAD

**Issue by mdrain** [swar8080/obsidian-plugin-update-tracker#18]
When I start Obsidian (v1.0.3) with the standard theme, the Plugin Update Tracker icon appears on the left of the status bar:

![image](https://user-images.githubusercontent.com/24597626/201488543-fdb45f29-ca5c-4ab4-8440-32aea4281deb.png)

If I disable and then enable the plugin, the icon appears on the right:

![image](https://user-images.githubusercontent.com/24597626/201488562-cfe61c2a-f09d-4fea-bfe5-e03ebad53014.png)

It returns to the left when I restart Obsidian.

Is there any way to permanently keep the icon on the right? I prefer that location.

**Comment by swar8080** [comment]
For sure, just add this CSS as a custom snippet file in your vault:

```
.status-bar-item.plugin-obsidian-plugin-update-tracker {
	order: 100;
}
```

Here's how to get to that folder and enable the snippet:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/17691679/201489834-fc3708ce-8c86-4500-bd64-4052d9a25622.png">

**Comment by mdrain** [comment]
Awesome. Many thanks!
