### ISSUE TITLE
Enhancement Request: CSS to make icons larger

### ISSUE THREAD

**Issue by ms3056** [swar8080/obsidian-plugin-update-tracker#42]
Could you please expose a CSS attribute to allow us to create a snippet to make the icons larger?

**Comment by swar8080** [comment]
Hey I can add this the next time there's a release, but in the mean time these selectors should work:

`.plugin-update-tracker-icon svg` for the plug icon

`.plugin-update-tracker-icon > div` for the status icon beside the plug icon (ex: the circle with a green checkmark)

I'm wondering if others are also finding things too small. Is the update count / status icon not visible enough on your screen?

**Comment by ms3056** [comment]
Thanks. I use a hi-res monitor and my eyesight is getting worse as I get older - so maybe this is just for me. The two selectors worked great and I'm happy leaving it at this 🙂 Thank you!
