### ISSUE TITLE
[Bug] Updates to latest version instead of showed versions in changelog

### ISSUE THREAD

**Issue by meskill** [swar8080/obsidian-plugin-update-tracker#48]
I have set up a setting "Days until new plugin versions are shown" and only versions that were released before that day are shown in the updates tab. 

# Actual 

After picking plugins to update they got updated to their latest version instead of showed versions. And I don't know the actual changelog in plugins that I've got.

# Expected

Either plugins should be updated to showed versions not the latest or this setting shouldn't exist as it has misleading behaviour

**Comment by swar8080** [comment]
Just pushed a fix, thanks for reporting!
