### ISSUE TITLE
Update button not reachable on iPhone 14 Pro Max

### ISSUE THREAD

**Issue by haemi** [swar8080/obsidian-plugin-update-tracker#49]
Hey,

first of all thanks for the plugin, really great!

On my iPhone I have the problem that I can't reach the update button when selecting plugins to update. I'm using the latest version of Obsidian with the default theme.

![IMG_0954](https://user-images.githubusercontent.com/183958/211282419-edfa69e4-6828-4cf5-9590-3fde84be01f0.PNG)

**Comment by swar8080** [comment]
I didn't have an iphone to test but this should be fixed in the latest version

thanks for reporting
