### ISSUE TITLE
FR: Treshold of Updates before Counter is shown

### ISSUE THREAD

**Issue by chrisgrieser** [swar8080/obsidian-plugin-update-tracker#55]
Right now, there is only the option to hide the status bar item when there is no update. However, I'd find it quite useful if you could configure a *threshold* number: For example, only when x plugins have updates available, the indicator shows up in the status bar to remind you

**Comment by swar8080** [comment]
This is implemented in v1.5.0

**Comment by chrisgrieser** [comment]
thank yo 😊
