### ISSUE TITLE
FR: Change polling time

### ISSUE THREAD

**Issue by LordFarquhar** [swar8080/obsidian-plugin-update-tracker#58]
Would love the ability to modify the polling time from within the options menu
I find it is far too often for my liking

I feel this could be implemented in a similar way to the "Days until..." option, simply as a number of minutes between polls

![image](https://user-images.githubusercontent.com/65400619/226694445-e9e63d57-d4ac-4a21-b7a2-1b1f3bbe039a.png)

**Comment by coder-user** [comment]
Yes, preferably one that requires support for polling times

**Comment by swar8080** [comment]
This is implemented in v1.5.0

Let me know if there's any issues
