### ISSUE TITLE
Update Tracker Does Not Show Settings Option Nor Work When Enabled

### ISSUE THREAD

**Issue by johnkferguson** [swar8080/obsidian-plugin-update-tracker#65]
Hi,

I recently installed the Plugin Update Tracker (version 1.5.0). into Obsidian version 1.3.4 on a Windows 10 computer. I had not used this plugin before so it is a fresh install.

After enabling the plugin, there is no option to adjust settings as you can see in the screenshot below:

<img width="602" alt="plugin-update-tracker-no-options" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/2823694/3a1e253b-98a0-47d9-b4bb-652babaa95e2">

Additionally, the plugin doesn't show any updates for any plugins. Some updates for my other plugins have been released since installing the update tracked but there has been no notification or anything like that about these updates.

I have tried replicating it in a completely fresh vault on the same PC with no other plugins or changes to settings and it still does not show any way of accessing the settings page.

**Comment by swar8080** [comment]
Thanks for reporting this and trying to debug the issue

The bug's fixed in the latest version 1.5.1

**Comment by johnkferguson** [comment]
Great, just tested it and it works. Thanks for the quick fix. 😄
