### ISSUE TITLE
Bug: Treshhold for the Counter to show not working

### ISSUE THREAD

**Issue by chrisgrieser** [swar8080/obsidian-plugin-update-tracker#67]
![CleanShot 2023-05-29 at 11 34 36@2x](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/73286100/f9c097cb-66d0-46bf-a99a-61ab7762c7a3)
![CleanShot 2023-05-29 at 11 34 49@2x](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/73286100/d1c7c6e8-6d5f-4536-a0ad-9a868360377e)

**Comment by swar8080** [comment]
Hi Chris, is that an update for this plugin? 

If so, I made the icon always show if this plugin has an update. That's in case there's ever a bug causing the update count  I'll mention this in the plugin setting's description the next time there's a release

**Comment by chrisgrieser** [comment]
oh, I see. yeah, it was. Guess that makes this comment obsolete 👍
