### ISSUE TITLE
No updates can't click？

### ISSUE THREAD

**Issue by jerviscui** [swar8080/obsidian-plugin-update-tracker#7]
Nothing happens when you click on plugins not updated, right?

**Comment by swar8080** [comment]
Yep, clicking the plugin icon does nothing when all installed plugins are up-to-date. The README's been updated to make that clear - thanks

Is there anything you'd like to see after clicking the icon in this case though? Let me know if you have any suggestions

**Comment by jerviscui** [comment]
I just need confirmation and information for those who come after me.

Glad you'll update README's .
