### ISSUE TITLE
Plugins Refresh but not the "Check for updates" button in main editor settings

### ISSUE THREAD

**Issue by Net-Slayer** [swar8080/obsidian-plugin-update-tracker#71]
### Description
The Community plugin's settings do refresh in the window! 
However the "Check for updates" button will still be seen as "Update all".
This could make one believe the updates from plugin tracker have not been applied.

### Steps to Reproduce
1. In Obsidian, go to:  Settings > Community Plugins
2. Next to Current Plugins: Click the "Check for updates" button.
3. If there are updates pending it will highlight with "Update All"
4. Exit settings and go to the status bar, selecting the Plugin Update Tracker Icon. (Out of curiosity)
5. Examine changelogs and update all, allowing the process to finish.
6. Exit the plugin tracker and reopen Settings > Community Plugins
7. **Next to Current Plugins: "Update All" is still present.**

### Expected Behavior
"Update All" button should revert back to "Check for updates"

### Actual Behavior
Plugin settings accessed from Settings > Community Plugins show that the updates from the Plugin Update tracker page have applied.
However the Check for updates button remains stuck as "Update All"

### Environment
Operating System: Windows 10 Home 64-bit
Obsidian: 1.3.5

### Extra Notes
I'm unsure if this can be achieved through development on this plugin, somehow the plugins settings are refreshed in menu and I was hoping that perhaps the Community Plugins section could also be refreshed?
If it's actually an obsidian issue I'll make the report there.
Thank you for such a fantastic plugin!

**Comment by swar8080** [comment]
Hey good catch and thanks for the detailed report

Plugins aren't really supposed to change the state of undocumented parts of the UI like this - it could break things or stop working in future obsidian updates
