### ISSUE TITLE
Cursor style is set to "none"

### ISSUE THREAD

**Issue by Mikle-Bond** [swar8080/obsidian-plugin-update-tracker#72]
I see that cursor is meant to change when hovering over plugin icon. But when there are no plugin updates, the cursor disappears. Is that an intended behavior? I personally see this as a bug, because cursor shouldn't disappear without explicit reason.

I believe [this](https://github.com/swar8080/obsidian-plugin-update-tracker/blob/master/src/components/UpdateStatusIcon.tsx#L121) is where such behavior originates from. Can we change it to `'default'` or is it meant to be `'none'` for some other reason?

**Comment by swar8080** [comment]
Hi, thanks for reporting

The cursor was removed to make it clearer that nothing happens when clicking the icon if there's no updates. Someone was confused by the cursor in #7. I can't think of anything useful to display when there's no updates but let me know if you have suggestions about how to handle this

**Comment by Mikle-Bond** [comment]
Ah, I see. But hiding cursor is still not the way, IMHO. Because now my cursor disappears right before i want to change the size of Obsidian's window)

Proposal: I think it would be better if a new modal window was added, with a big green circle with a confirmation tick, and something like "All plugins are up to date!". That'd fit as a solution to my confusion, and for our colleague from #7 

> Explicit is better than implicit.

Yes, I know there's a pop-up with this *exact* same purpose and text (even two of them on my machine, dunno why, see screenshot below), but a little feedback on click would improve UX slightly.

![screenshot](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/5671588/dac33b1a-b9af-484c-811a-fc3997bcd0e4)

**Comment by swar8080** [comment]
that makes sense, a toast/[notice](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L2665) icon seems like a good fit for that message

i'll get around to implementing this at some point

**Comment by swar8080** [comment]
Improved this in the latest release, thanks for reporting
