### ISSUE TITLE
Many plugins refuse update - while others did fine

### ISSUE THREAD

**Issue by Sigbert11** [swar8080/obsidian-plugin-update-tracker#73]
<img width="464" alt="Screenshot of Obsidian" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/84449137/94f9da5a-d74f-4157-a97e-2d2e309fdb7f">

### What happened 
- came back to Obsidian after a 2 weeks break. Obsidian 1.4.2 seemed to be freshly updated.
- trying to update over 20 plugins left about half of them untouched with an error message (see screenshot)
- of course tried repeatedly after a while, including restart of obsidian 
- this never happened before 

### anything to be done about?
- is there a max number of updates to run at the same time
- user mistake from my side? 
- update-tracker-bug?
- these plugins suddenly not fully compatible?

Any suggestion welcome ...

**Comment by swar8080** [comment]
Hey that error message is expected when your IP address has made too many API calls to github. The limit is 60 requests per hour, and each plugin update makes 2-3 API calls to download the new code. The blocked API call responses mention when the limit is reset, which is where the "5 minutes" comes from in that error message.

Are you continually getting this error? Possibly you or someone else on that IP is making github API calls?

**Comment by swar8080** [comment]
Made the error message clearer, thanks for reporting
