### ISSUE TITLE
Feature Request: Current plugin list inserted as table

### ISSUE THREAD

**Issue by Aetherinox** [swar8080/obsidian-plugin-update-tracker#75]
It would be a rather simple feature, but I would love to have this addon also be able to print off a list of **currently installed plugins** and insert them into a table within your Obsidian vault.

![8QIO1eA](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/118329232/23cb14b7-712d-4a62-85b5-7ceff1893c81)

I frequently change which plugins I have, and I like to keep a list of what they are, and the version installed, due to me having multiple vaults where I have to keep tracking plugins I need to migrate over, and which ones I don't want.

The insert functionality could be as simple as a new option when you right-click in your obsidian note and it just list **"Insert Plugin List"**

![EexfzPp](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/118329232/b65f96ff-e200-47c3-b32f-14297f9d6f38)

If ya want to go a step up, maybe throw in the description of the plugin, even with a character limit (truncate) of like the first 100 chars. Would just make this sort of thing much more easy. Right now I'm having to manually edit the list and compare plugins like once a month, and it's a pain.

**Comment by swar8080** [comment]
Hello, thanks for reporting

Have you seen the _Debug Info_ dialogue built-in to obsidian? It lists enabled plugins and their versions which might help:

<img width="809" alt="image" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/17691679/e41414cc-6ca2-45ef-a0a8-c7ba773ad33d">
