### ISSUE TITLE
FR: Ability to hide “Error checking for plugin updates” notification

### ISSUE THREAD

**Issue by nhan000** [swar8080/obsidian-plugin-update-tracker#78]
I get this notification quite a bit, when my internet goes in and out, or when I put my PC to sleep.

![image](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/85216095/bb13c033-5e71-4fb9-816d-d7e246d68726)

It's distracting to me so I'd like to have the ability to disable this type of notification. I also think it's better to use a different color than red which is used to notify that there're plugin updates, to have less ambiguity at a glance.

Thanks a lot!

**Comment by swar8080** [comment]
Hey @nhan000, the icon can be hidden when in the error state with this [custom css snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets):

```
.plugin-obsidian-plugin-update-tracker .plugin-update-tracker-icon--error {
	display: none;
}
```

**Comment by nhan000** [comment]
Thanks for the quick reply! This will do it for me :D
