### ISSUE TITLE
Incorrect results for Periodic Notes and Dynamic Highlights

### ISSUE THREAD

**Issue by ms3056** [swar8080/obsidian-plugin-update-tracker#8]
For Periodic Notes: your plugin suggests upgrading from 0.0.17 → 1.0.0-beta.3. When you click nothing changes and your plugin continues to suggest this upgrade, even when restarting Obsidian. 

For Dynamic Highlights: your plugin suggests upgrading from 0.3.1 → 0.2.5. When you do this the plugin will no longer load. Luckily I backed up my settings 🙂 

![2022-10-31_11h29_15](https://user-images.githubusercontent.com/23712700/198918834-3946f742-7827-446c-848d-4a0bb89731b5.png)

**Comment by swar8080** [comment]
Fixed both issues, thanks for reporting

No need to update this plugin since it was a backend change

**Comment by ms3056** [comment]
Working great on my end, thank you! This is a very cool plugin!

**Comment by swar8080** [comment]
@ms3056 you will have to download a new version (1.0.1) after all

thanks again
