### ISSUE TITLE
Beta versions is not ignored

### ISSUE THREAD

**Issue by vanbang9710** [swar8080/obsidian-plugin-update-tracker#81]
I turn on the settings to ignore beta versions but it doesn't work. [An example plugin](https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/) ![|50pct](https://i.imgur.com/HVjJm0Y.png)

**Comment by swar8080** [comment]
Thanks for reporting, I just pushed a fix to the backend so these will now be considered beta versions. The existing logic was solely checking for the beta version convention used with https://github.com/TfTHacker/obsidian42-brat. It'll now also check for the words `beta` and `alpha` in the version number
