### ISSUE TITLE
Error Checking for Plugin Updates

### ISSUE THREAD

**Issue by jvdevlab** [swar8080/obsidian-plugin-update-tracker#85]
I see this pretty much all the time. I think this is happening because PC goes to sleep or some other reason 

![image](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/83979897/8cb06d6a-d46c-46e8-8422-f955b943e19c)

`
plugin:obsidian-plug…-update-tracker:800 Failed checking for plugin updates at https://jc5gpa3gs7o2uge6iq5mgjd53q0daomi.lambda-url.us-east-1.on.aws/obsidian-plugin-update-tracker. Check your internet connection and security settings or file a bug at https://github.com/swar8080/obsidian-plugin-update-tracker/issues.
Error details are:
 Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
`

When it is in that state and I press on the update icon I always get 
![image](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/83979897/b37b8eb3-ab06-4d34-9349-7e3b46fe63c9)

I have to restart Obsidian or the plugin for it to work again.

Don't know what the connection logic right now. But maybe it needs some fix to get out of these state when it gets into it.

**Comment by swar8080** [comment]
By default the plugin checks for updates when obsidian starts and every 30 minutes after that

But yeah it's not clear how to force a refresh when this happens. Maybe forcing a refresh when clicking the error icon is a solution

I'll leave this open for now

Thanks for reporting

**Comment by jvdevlab** [comment]
>Maybe forcing a refresh when clicking the error icon is a solution
Yes, that would help. Thanks!

**Comment by NaturallyAsh** [comment]
Any progress with this? I'm also experiencing the same issue and would like an option to "force refresh."

**Comment by swar8080** [comment]
A workaround is restarting obsidian using an action or hotkey:
<img width="789" alt="image" src="https://github.com/swar8080/obsidian-plugin-update-tracker/assets/17691679/73c9c1ca-072a-4807-b330-0b87f23d34e9">

**Comment by juanbretti** [comment]
> A workaround is restarting obsidian using an action or hotkey: <img alt="image" width="789" src="https://private-user-images.githubusercontent.com/17691679/316361885-73c9c1ca-072a-4807-b330-0b87f23d34e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjg2NzAsIm5iZiI6MTcyMTAyODM3MCwicGF0aCI6Ii8xNzY5MTY3OS8zMTYzNjE4ODUtNzNjOWMxY2EtMDcyYS00ODA3LWIzMzAtMGI4N2YyM2QzNGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA3MjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NWUxYjlkZjJiYzMxZGZmNjhiNGZiOTljNDc0ZGY0OGIyYjJiMWY0YTUzNDM2MzEzYjRhNWNmYzY0NDAyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kdVaOEGUDbdxtECO1bxyQwxso09gFwcQujA6rMsbziM">

Same issue here, but the **Reload app without saving** solves it.

**Comment by arteny** [comment]
Same issue, only restart helps. 
Is it going to be fixed?

**Comment by profucius** [comment]
I am having this issue too, however restarting/reloading the app does not resolve it. As soon as the app displays again, the plugin does not work. Same screenshot from OP. Is it dead? I'm on Obsidian v1.7.3

**Comment by juanbretti** [comment]
> Is it dead? I'm on Obsidian v1.7.3

Works for me in the same version.
Are you behind any proxy, vpn or corporate network?

**Comment by profucius** [comment]
Yep that was it, it was my DNS filter. I'll have to diagnose it internally. I can access Github fine otherwise. Thanks.
