### ISSUE TITLE
Wrong CSS selector

### ISSUE THREAD

**Issue by hmijail** [swar8080/obsidian-plugin-update-tracker#97]
The README says this:
> .status-bar-item.plugin-update-tracker-icon--no-updates-available: Plugin icon container when no updates are available (✓)

In my case, that selector doesn't seem to exist. I needed to add a space between the 2 classes:
`.status-bar-item .plugin-update-tracker-icon--no-updates-available`

Confusingly, the selector used in the examples (`.status-bar-item.plugin-obsidian-plugin-update-tracker`) works fine. 

I didn't check the rest of selectors.

**Comment by swar8080** [comment]
Updated the CSS selectors. Thank you
